/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_GYMJOT_CUFF_PROTO_CUFF_PB_H_INCLUDED
#define PB_COM_GYMJOT_CUFF_PROTO_CUFF_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _com_gymjot_cuff_DeviceMode {
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_IDLE = 0,
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_AWAITING_STATION = 1,
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_SCANNING = 2,
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_LOITER = 3
} com_gymjot_cuff_DeviceMode;

/* Struct definitions */
typedef struct _com_gymjot_cuff_MetadataEntry {
    char key[33];
    char value[97];
} com_gymjot_cuff_MetadataEntry;

typedef struct _com_gymjot_cuff_StationMetadata {
    pb_size_t entries_count;
    com_gymjot_cuff_MetadataEntry entries[10];
} com_gymjot_cuff_StationMetadata;

typedef struct _com_gymjot_cuff_SetTestModeCommand {
    bool enabled;
} com_gymjot_cuff_SetTestModeCommand;

typedef struct _com_gymjot_cuff_SetTargetFpsCommand {
    float fps;
} com_gymjot_cuff_SetTargetFpsCommand;

typedef struct _com_gymjot_cuff_StationUpdateCommand {
    uint32_t station_id;
    char name[65];
    bool has_metadata;
    com_gymjot_cuff_StationMetadata metadata;
    bool set_min_travel_cm;
    float min_travel_cm;
    bool set_fps;
    float fps;
} com_gymjot_cuff_StationUpdateCommand;

typedef struct _com_gymjot_cuff_ResetRepsCommand {
    char dummy_field;
} com_gymjot_cuff_ResetRepsCommand;

typedef struct _com_gymjot_cuff_DeviceCommand {
    uint64_t timestamp_ms;
    pb_size_t which_command;
    union {
        com_gymjot_cuff_SetTestModeCommand set_test_mode;
        com_gymjot_cuff_SetTargetFpsCommand set_target_fps;
        com_gymjot_cuff_StationUpdateCommand station_update;
        com_gymjot_cuff_ResetRepsCommand reset_reps;
    } command;
} com_gymjot_cuff_DeviceCommand;

typedef struct _com_gymjot_cuff_BootEvent {
    bool test_mode;
    com_gymjot_cuff_DeviceMode mode;
    float fps;
} com_gymjot_cuff_BootEvent;

typedef struct _com_gymjot_cuff_StatusEvent {
    char status_label[33];
    com_gymjot_cuff_DeviceMode mode;
    float fps;
    bool test_mode;
} com_gymjot_cuff_StatusEvent;

typedef struct _com_gymjot_cuff_TagEvent {
    uint32_t tag_id;
    bool from_test_mode;
} com_gymjot_cuff_TagEvent;

typedef struct _com_gymjot_cuff_StationRequestEvent {
    uint32_t tag_id;
} com_gymjot_cuff_StationRequestEvent;

typedef struct _com_gymjot_cuff_StationBroadcastEvent {
    uint32_t station_id;
    char name[65];
    bool has_metadata;
    com_gymjot_cuff_StationMetadata metadata;
    bool from_test_mode;
} com_gymjot_cuff_StationBroadcastEvent;

typedef struct _com_gymjot_cuff_StationReadyEvent {
    uint32_t station_id;
} com_gymjot_cuff_StationReadyEvent;

typedef struct _com_gymjot_cuff_ScanEvent {
    uint32_t tag_id;
    float distance_cm;
    com_gymjot_cuff_DeviceMode mode;
    float fps;
    bool has_station_name;
    char station_name[65];
} com_gymjot_cuff_ScanEvent;

typedef struct _com_gymjot_cuff_RepEvent {
    uint32_t tag_id;
    uint32_t rep_count;
    bool has_station_name;
    char station_name[65];
} com_gymjot_cuff_RepEvent;

typedef struct _com_gymjot_cuff_DeviceEvent {
    uint64_t timestamp_ms;
    pb_size_t which_event;
    union {
        com_gymjot_cuff_BootEvent boot;
        com_gymjot_cuff_StatusEvent status;
        com_gymjot_cuff_TagEvent tag;
        com_gymjot_cuff_StationRequestEvent station_request;
        com_gymjot_cuff_StationBroadcastEvent station_broadcast;
        com_gymjot_cuff_ScanEvent scan;
        com_gymjot_cuff_RepEvent rep;
        com_gymjot_cuff_StationReadyEvent station_ready;
    } event;
} com_gymjot_cuff_DeviceEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _com_gymjot_cuff_DeviceMode_MIN com_gymjot_cuff_DeviceMode_DEVICE_MODE_IDLE
#define _com_gymjot_cuff_DeviceMode_MAX com_gymjot_cuff_DeviceMode_DEVICE_MODE_LOITER
#define _com_gymjot_cuff_DeviceMode_ARRAYSIZE ((com_gymjot_cuff_DeviceMode)(com_gymjot_cuff_DeviceMode_DEVICE_MODE_LOITER+1))









#define com_gymjot_cuff_BootEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode

#define com_gymjot_cuff_StatusEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode





#define com_gymjot_cuff_ScanEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode



/* Initializer values for message structs */
#define com_gymjot_cuff_MetadataEntry_init_default {"", ""}
#define com_gymjot_cuff_StationMetadata_init_default {0, {com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default}}
#define com_gymjot_cuff_DeviceCommand_init_default {0, 0, {com_gymjot_cuff_SetTestModeCommand_init_default}}
#define com_gymjot_cuff_SetTestModeCommand_init_default {0}
#define com_gymjot_cuff_SetTargetFpsCommand_init_default {0}
#define com_gymjot_cuff_StationUpdateCommand_init_default {0, "", false, com_gymjot_cuff_StationMetadata_init_default, 0, 0, 0, 0}
#define com_gymjot_cuff_ResetRepsCommand_init_default {0}
#define com_gymjot_cuff_DeviceEvent_init_default {0, 0, {com_gymjot_cuff_BootEvent_init_default}}
#define com_gymjot_cuff_BootEvent_init_default   {0, _com_gymjot_cuff_DeviceMode_MIN, 0}
#define com_gymjot_cuff_StatusEvent_init_default {"", _com_gymjot_cuff_DeviceMode_MIN, 0, 0}
#define com_gymjot_cuff_TagEvent_init_default    {0, 0}
#define com_gymjot_cuff_StationRequestEvent_init_default {0}
#define com_gymjot_cuff_StationBroadcastEvent_init_default {0, "", false, com_gymjot_cuff_StationMetadata_init_default, 0}
#define com_gymjot_cuff_StationReadyEvent_init_default {0}
#define com_gymjot_cuff_ScanEvent_init_default   {0, 0, _com_gymjot_cuff_DeviceMode_MIN, 0, 0, ""}
#define com_gymjot_cuff_RepEvent_init_default    {0, 0, 0, ""}
#define com_gymjot_cuff_MetadataEntry_init_zero  {"", ""}
#define com_gymjot_cuff_StationMetadata_init_zero {0, {com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero}}
#define com_gymjot_cuff_DeviceCommand_init_zero  {0, 0, {com_gymjot_cuff_SetTestModeCommand_init_zero}}
#define com_gymjot_cuff_SetTestModeCommand_init_zero {0}
#define com_gymjot_cuff_SetTargetFpsCommand_init_zero {0}
#define com_gymjot_cuff_StationUpdateCommand_init_zero {0, "", false, com_gymjot_cuff_StationMetadata_init_zero, 0, 0, 0, 0}
#define com_gymjot_cuff_ResetRepsCommand_init_zero {0}
#define com_gymjot_cuff_DeviceEvent_init_zero    {0, 0, {com_gymjot_cuff_BootEvent_init_zero}}
#define com_gymjot_cuff_BootEvent_init_zero      {0, _com_gymjot_cuff_DeviceMode_MIN, 0}
#define com_gymjot_cuff_StatusEvent_init_zero    {"", _com_gymjot_cuff_DeviceMode_MIN, 0, 0}
#define com_gymjot_cuff_TagEvent_init_zero       {0, 0}
#define com_gymjot_cuff_StationRequestEvent_init_zero {0}
#define com_gymjot_cuff_StationBroadcastEvent_init_zero {0, "", false, com_gymjot_cuff_StationMetadata_init_zero, 0}
#define com_gymjot_cuff_StationReadyEvent_init_zero {0}
#define com_gymjot_cuff_ScanEvent_init_zero      {0, 0, _com_gymjot_cuff_DeviceMode_MIN, 0, 0, ""}
#define com_gymjot_cuff_RepEvent_init_zero       {0, 0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define com_gymjot_cuff_MetadataEntry_key_tag    1
#define com_gymjot_cuff_MetadataEntry_value_tag  2
#define com_gymjot_cuff_StationMetadata_entries_tag 1
#define com_gymjot_cuff_SetTestModeCommand_enabled_tag 1
#define com_gymjot_cuff_SetTargetFpsCommand_fps_tag 1
#define com_gymjot_cuff_StationUpdateCommand_station_id_tag 1
#define com_gymjot_cuff_StationUpdateCommand_name_tag 2
#define com_gymjot_cuff_StationUpdateCommand_metadata_tag 3
#define com_gymjot_cuff_StationUpdateCommand_set_min_travel_cm_tag 4
#define com_gymjot_cuff_StationUpdateCommand_min_travel_cm_tag 5
#define com_gymjot_cuff_StationUpdateCommand_set_fps_tag 6
#define com_gymjot_cuff_StationUpdateCommand_fps_tag 7
#define com_gymjot_cuff_DeviceCommand_timestamp_ms_tag 1
#define com_gymjot_cuff_DeviceCommand_set_test_mode_tag 10
#define com_gymjot_cuff_DeviceCommand_set_target_fps_tag 11
#define com_gymjot_cuff_DeviceCommand_station_update_tag 12
#define com_gymjot_cuff_DeviceCommand_reset_reps_tag 13
#define com_gymjot_cuff_BootEvent_test_mode_tag  1
#define com_gymjot_cuff_BootEvent_mode_tag       2
#define com_gymjot_cuff_BootEvent_fps_tag        3
#define com_gymjot_cuff_StatusEvent_status_label_tag 1
#define com_gymjot_cuff_StatusEvent_mode_tag     2
#define com_gymjot_cuff_StatusEvent_fps_tag      3
#define com_gymjot_cuff_StatusEvent_test_mode_tag 4
#define com_gymjot_cuff_TagEvent_tag_id_tag      1
#define com_gymjot_cuff_TagEvent_from_test_mode_tag 2
#define com_gymjot_cuff_StationRequestEvent_tag_id_tag 1
#define com_gymjot_cuff_StationBroadcastEvent_station_id_tag 1
#define com_gymjot_cuff_StationBroadcastEvent_name_tag 2
#define com_gymjot_cuff_StationBroadcastEvent_metadata_tag 3
#define com_gymjot_cuff_StationBroadcastEvent_from_test_mode_tag 4
#define com_gymjot_cuff_StationReadyEvent_station_id_tag 1
#define com_gymjot_cuff_ScanEvent_tag_id_tag     1
#define com_gymjot_cuff_ScanEvent_distance_cm_tag 2
#define com_gymjot_cuff_ScanEvent_mode_tag       3
#define com_gymjot_cuff_ScanEvent_fps_tag        4
#define com_gymjot_cuff_ScanEvent_has_station_name_tag 5
#define com_gymjot_cuff_ScanEvent_station_name_tag 6
#define com_gymjot_cuff_RepEvent_tag_id_tag      1
#define com_gymjot_cuff_RepEvent_rep_count_tag   2
#define com_gymjot_cuff_RepEvent_has_station_name_tag 3
#define com_gymjot_cuff_RepEvent_station_name_tag 4
#define com_gymjot_cuff_DeviceEvent_timestamp_ms_tag 1
#define com_gymjot_cuff_DeviceEvent_boot_tag     10
#define com_gymjot_cuff_DeviceEvent_status_tag   11
#define com_gymjot_cuff_DeviceEvent_tag_tag      12
#define com_gymjot_cuff_DeviceEvent_station_request_tag 13
#define com_gymjot_cuff_DeviceEvent_station_broadcast_tag 14
#define com_gymjot_cuff_DeviceEvent_scan_tag     15
#define com_gymjot_cuff_DeviceEvent_rep_tag      16
#define com_gymjot_cuff_DeviceEvent_station_ready_tag 17

/* Struct field encoding specification for nanopb */
#define com_gymjot_cuff_MetadataEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define com_gymjot_cuff_MetadataEntry_CALLBACK NULL
#define com_gymjot_cuff_MetadataEntry_DEFAULT NULL

#define com_gymjot_cuff_StationMetadata_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  entries,           1)
#define com_gymjot_cuff_StationMetadata_CALLBACK NULL
#define com_gymjot_cuff_StationMetadata_DEFAULT NULL
#define com_gymjot_cuff_StationMetadata_entries_MSGTYPE com_gymjot_cuff_MetadataEntry

#define com_gymjot_cuff_DeviceCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_test_mode,command.set_test_mode),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_target_fps,command.set_target_fps),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,station_update,command.station_update),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,reset_reps,command.reset_reps),  13)
#define com_gymjot_cuff_DeviceCommand_CALLBACK NULL
#define com_gymjot_cuff_DeviceCommand_DEFAULT NULL
#define com_gymjot_cuff_DeviceCommand_command_set_test_mode_MSGTYPE com_gymjot_cuff_SetTestModeCommand
#define com_gymjot_cuff_DeviceCommand_command_set_target_fps_MSGTYPE com_gymjot_cuff_SetTargetFpsCommand
#define com_gymjot_cuff_DeviceCommand_command_station_update_MSGTYPE com_gymjot_cuff_StationUpdateCommand
#define com_gymjot_cuff_DeviceCommand_command_reset_reps_MSGTYPE com_gymjot_cuff_ResetRepsCommand

#define com_gymjot_cuff_SetTestModeCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1)
#define com_gymjot_cuff_SetTestModeCommand_CALLBACK NULL
#define com_gymjot_cuff_SetTestModeCommand_DEFAULT NULL

#define com_gymjot_cuff_SetTargetFpsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               1)
#define com_gymjot_cuff_SetTargetFpsCommand_CALLBACK NULL
#define com_gymjot_cuff_SetTargetFpsCommand_DEFAULT NULL

#define com_gymjot_cuff_StationUpdateCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   station_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          3) \
X(a, STATIC,   SINGULAR, BOOL,     set_min_travel_cm,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    min_travel_cm,     5) \
X(a, STATIC,   SINGULAR, BOOL,     set_fps,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               7)
#define com_gymjot_cuff_StationUpdateCommand_CALLBACK NULL
#define com_gymjot_cuff_StationUpdateCommand_DEFAULT NULL
#define com_gymjot_cuff_StationUpdateCommand_metadata_MSGTYPE com_gymjot_cuff_StationMetadata

#define com_gymjot_cuff_ResetRepsCommand_FIELDLIST(X, a) \

#define com_gymjot_cuff_ResetRepsCommand_CALLBACK NULL
#define com_gymjot_cuff_ResetRepsCommand_DEFAULT NULL

#define com_gymjot_cuff_DeviceEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,boot,event.boot),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,status,event.status),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,tag,event.tag),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,station_request,event.station_request),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,station_broadcast,event.station_broadcast),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,scan,event.scan),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,rep,event.rep),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,station_ready,event.station_ready),  17)
#define com_gymjot_cuff_DeviceEvent_CALLBACK NULL
#define com_gymjot_cuff_DeviceEvent_DEFAULT NULL
#define com_gymjot_cuff_DeviceEvent_event_boot_MSGTYPE com_gymjot_cuff_BootEvent
#define com_gymjot_cuff_DeviceEvent_event_status_MSGTYPE com_gymjot_cuff_StatusEvent
#define com_gymjot_cuff_DeviceEvent_event_tag_MSGTYPE com_gymjot_cuff_TagEvent
#define com_gymjot_cuff_DeviceEvent_event_station_request_MSGTYPE com_gymjot_cuff_StationRequestEvent
#define com_gymjot_cuff_DeviceEvent_event_station_broadcast_MSGTYPE com_gymjot_cuff_StationBroadcastEvent
#define com_gymjot_cuff_DeviceEvent_event_scan_MSGTYPE com_gymjot_cuff_ScanEvent
#define com_gymjot_cuff_DeviceEvent_event_rep_MSGTYPE com_gymjot_cuff_RepEvent
#define com_gymjot_cuff_DeviceEvent_event_station_ready_MSGTYPE com_gymjot_cuff_StationReadyEvent

#define com_gymjot_cuff_BootEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     test_mode,         1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               3)
#define com_gymjot_cuff_BootEvent_CALLBACK NULL
#define com_gymjot_cuff_BootEvent_DEFAULT NULL

#define com_gymjot_cuff_StatusEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   status_label,      1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               3) \
X(a, STATIC,   SINGULAR, BOOL,     test_mode,         4)
#define com_gymjot_cuff_StatusEvent_CALLBACK NULL
#define com_gymjot_cuff_StatusEvent_DEFAULT NULL

#define com_gymjot_cuff_TagEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, BOOL,     from_test_mode,    2)
#define com_gymjot_cuff_TagEvent_CALLBACK NULL
#define com_gymjot_cuff_TagEvent_DEFAULT NULL

#define com_gymjot_cuff_StationRequestEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1)
#define com_gymjot_cuff_StationRequestEvent_CALLBACK NULL
#define com_gymjot_cuff_StationRequestEvent_DEFAULT NULL

#define com_gymjot_cuff_StationBroadcastEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   station_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          3) \
X(a, STATIC,   SINGULAR, BOOL,     from_test_mode,    4)
#define com_gymjot_cuff_StationBroadcastEvent_CALLBACK NULL
#define com_gymjot_cuff_StationBroadcastEvent_DEFAULT NULL
#define com_gymjot_cuff_StationBroadcastEvent_metadata_MSGTYPE com_gymjot_cuff_StationMetadata

#define com_gymjot_cuff_StationReadyEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   station_id,        1)
#define com_gymjot_cuff_StationReadyEvent_CALLBACK NULL
#define com_gymjot_cuff_StationReadyEvent_DEFAULT NULL

#define com_gymjot_cuff_ScanEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_cm,       2) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               4) \
X(a, STATIC,   SINGULAR, BOOL,     has_station_name,   5) \
X(a, STATIC,   SINGULAR, STRING,   station_name,      6)
#define com_gymjot_cuff_ScanEvent_CALLBACK NULL
#define com_gymjot_cuff_ScanEvent_DEFAULT NULL

#define com_gymjot_cuff_RepEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   rep_count,         2) \
X(a, STATIC,   SINGULAR, BOOL,     has_station_name,   3) \
X(a, STATIC,   SINGULAR, STRING,   station_name,      4)
#define com_gymjot_cuff_RepEvent_CALLBACK NULL
#define com_gymjot_cuff_RepEvent_DEFAULT NULL

extern const pb_msgdesc_t com_gymjot_cuff_MetadataEntry_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StationMetadata_msg;
extern const pb_msgdesc_t com_gymjot_cuff_DeviceCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_SetTestModeCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_SetTargetFpsCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StationUpdateCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ResetRepsCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_DeviceEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_BootEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StatusEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_TagEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StationRequestEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StationBroadcastEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StationReadyEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ScanEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_RepEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_gymjot_cuff_MetadataEntry_fields &com_gymjot_cuff_MetadataEntry_msg
#define com_gymjot_cuff_StationMetadata_fields &com_gymjot_cuff_StationMetadata_msg
#define com_gymjot_cuff_DeviceCommand_fields &com_gymjot_cuff_DeviceCommand_msg
#define com_gymjot_cuff_SetTestModeCommand_fields &com_gymjot_cuff_SetTestModeCommand_msg
#define com_gymjot_cuff_SetTargetFpsCommand_fields &com_gymjot_cuff_SetTargetFpsCommand_msg
#define com_gymjot_cuff_StationUpdateCommand_fields &com_gymjot_cuff_StationUpdateCommand_msg
#define com_gymjot_cuff_ResetRepsCommand_fields &com_gymjot_cuff_ResetRepsCommand_msg
#define com_gymjot_cuff_DeviceEvent_fields &com_gymjot_cuff_DeviceEvent_msg
#define com_gymjot_cuff_BootEvent_fields &com_gymjot_cuff_BootEvent_msg
#define com_gymjot_cuff_StatusEvent_fields &com_gymjot_cuff_StatusEvent_msg
#define com_gymjot_cuff_TagEvent_fields &com_gymjot_cuff_TagEvent_msg
#define com_gymjot_cuff_StationRequestEvent_fields &com_gymjot_cuff_StationRequestEvent_msg
#define com_gymjot_cuff_StationBroadcastEvent_fields &com_gymjot_cuff_StationBroadcastEvent_msg
#define com_gymjot_cuff_StationReadyEvent_fields &com_gymjot_cuff_StationReadyEvent_msg
#define com_gymjot_cuff_ScanEvent_fields &com_gymjot_cuff_ScanEvent_msg
#define com_gymjot_cuff_RepEvent_fields &com_gymjot_cuff_RepEvent_msg

/* Maximum encoded size of messages (where known) */
#define COM_GYMJOT_CUFF_PROTO_CUFF_PB_H_MAX_SIZE com_gymjot_cuff_DeviceCommand_size
#define com_gymjot_cuff_BootEvent_size           9
#define com_gymjot_cuff_DeviceCommand_size       1453
#define com_gymjot_cuff_DeviceEvent_size         1441
#define com_gymjot_cuff_MetadataEntry_size       132
#define com_gymjot_cuff_RepEvent_size            80
#define com_gymjot_cuff_ResetRepsCommand_size    0
#define com_gymjot_cuff_ScanEvent_size           86
#define com_gymjot_cuff_SetTargetFpsCommand_size 5
#define com_gymjot_cuff_SetTestModeCommand_size  2
#define com_gymjot_cuff_StationBroadcastEvent_size 1427
#define com_gymjot_cuff_StationMetadata_size     1350
#define com_gymjot_cuff_StationReadyEvent_size   6
#define com_gymjot_cuff_StationRequestEvent_size 6
#define com_gymjot_cuff_StationUpdateCommand_size 1439
#define com_gymjot_cuff_StatusEvent_size         43
#define com_gymjot_cuff_TagEvent_size            8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
