/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COM_GYMJOT_CUFF_CUFF_PB_H_INCLUDED
#define PB_COM_GYMJOT_CUFF_CUFF_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _com_gymjot_cuff_DeviceMode {
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_IDLE = 0,
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_AWAITING_EXERCISE = 1,
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_SCANNING = 2,
    com_gymjot_cuff_DeviceMode_DEVICE_MODE_LOITER = 3
} com_gymjot_cuff_DeviceMode;

typedef enum _com_gymjot_cuff_OtaPhase {
    com_gymjot_cuff_OtaPhase_OTA_PHASE_IDLE = 0,
    com_gymjot_cuff_OtaPhase_OTA_PHASE_PREPARING = 1,
    com_gymjot_cuff_OtaPhase_OTA_PHASE_TRANSFER = 2,
    com_gymjot_cuff_OtaPhase_OTA_PHASE_APPLYING = 3,
    com_gymjot_cuff_OtaPhase_OTA_PHASE_ERROR = 4
} com_gymjot_cuff_OtaPhase;

/* Struct definitions */
typedef struct _com_gymjot_cuff_MetadataEntry {
    char key[33];
    char value[97];
} com_gymjot_cuff_MetadataEntry;

typedef struct _com_gymjot_cuff_ExerciseMetadata {
    pb_size_t entries_count;
    com_gymjot_cuff_MetadataEntry entries[10];
} com_gymjot_cuff_ExerciseMetadata;

typedef struct _com_gymjot_cuff_SetTestModeCommand {
    bool enabled;
} com_gymjot_cuff_SetTestModeCommand;

typedef struct _com_gymjot_cuff_SetTargetFpsCommand {
    float fps;
} com_gymjot_cuff_SetTargetFpsCommand;

typedef struct _com_gymjot_cuff_ExerciseUpdateCommand {
    uint32_t exercise_id;
    char name[65];
    bool has_metadata;
    com_gymjot_cuff_ExerciseMetadata metadata;
    bool set_min_travel_cm;
    float min_travel_cm;
    bool set_fps;
    float fps;
} com_gymjot_cuff_ExerciseUpdateCommand;

typedef struct _com_gymjot_cuff_ResetRepsCommand {
    char dummy_field;
} com_gymjot_cuff_ResetRepsCommand;

typedef struct _com_gymjot_cuff_PowerCommand {
    bool shutdown;
} com_gymjot_cuff_PowerCommand;

typedef struct _com_gymjot_cuff_FactoryResetCommand {
    bool confirm;
} com_gymjot_cuff_FactoryResetCommand;

typedef struct _com_gymjot_cuff_ClearBondsCommand {
    bool confirm;
} com_gymjot_cuff_ClearBondsCommand;

typedef struct _com_gymjot_cuff_SnapshotRequestCommand {
    char dummy_field;
} com_gymjot_cuff_SnapshotRequestCommand;

typedef struct _com_gymjot_cuff_TakePhotoCommand {
    bool high_resolution;
} com_gymjot_cuff_TakePhotoCommand;

typedef struct _com_gymjot_cuff_UpdateDeviceConfigCommand {
    bool set_target_fps;
    float target_fps;
    bool set_loiter_fps;
    float loiter_fps;
    bool set_min_travel_cm;
    float min_travel_cm;
    bool set_max_rep_idle_ms;
    uint32_t max_rep_idle_ms;
} com_gymjot_cuff_UpdateDeviceConfigCommand;

typedef struct _com_gymjot_cuff_OtaBeginCommand {
    uint32_t total_size;
    uint32_t chunk_size;
    char version[33];
    pb_callback_t sha256;
} com_gymjot_cuff_OtaBeginCommand;

typedef struct _com_gymjot_cuff_OtaChunkCommand {
    uint32_t offset;
    pb_callback_t data;
} com_gymjot_cuff_OtaChunkCommand;

typedef struct _com_gymjot_cuff_OtaCompleteCommand {
    bool apply;
} com_gymjot_cuff_OtaCompleteCommand;

typedef struct _com_gymjot_cuff_StartVideoCommand {
    float fps; /* Video frame rate (default: 5 fps) */
    bool enable_apriltag_detection; /* Enable AprilTag detection in video frames */
    bool enable_motion_detection; /* Enable motion detection */
} com_gymjot_cuff_StartVideoCommand;

typedef struct _com_gymjot_cuff_StopVideoCommand {
    char dummy_field;
} com_gymjot_cuff_StopVideoCommand;

typedef struct _com_gymjot_cuff_DeviceCommand {
    uint64_t timestamp_ms;
    pb_size_t which_command;
    union {
        com_gymjot_cuff_SetTestModeCommand set_test_mode;
        com_gymjot_cuff_SetTargetFpsCommand set_target_fps;
        com_gymjot_cuff_ExerciseUpdateCommand exercise_update;
        com_gymjot_cuff_ResetRepsCommand reset_reps;
        com_gymjot_cuff_PowerCommand power;
        com_gymjot_cuff_FactoryResetCommand factory_reset;
        com_gymjot_cuff_SnapshotRequestCommand snapshot_request;
        com_gymjot_cuff_UpdateDeviceConfigCommand update_device_config;
        com_gymjot_cuff_OtaBeginCommand ota_begin;
        com_gymjot_cuff_OtaChunkCommand ota_chunk;
        com_gymjot_cuff_OtaCompleteCommand ota_complete;
        com_gymjot_cuff_ClearBondsCommand clear_bonds;
        com_gymjot_cuff_TakePhotoCommand take_photo;
        com_gymjot_cuff_StartVideoCommand start_video;
        com_gymjot_cuff_StopVideoCommand stop_video;
    } command;
} com_gymjot_cuff_DeviceCommand;

typedef struct _com_gymjot_cuff_BootEvent {
    bool test_mode;
    com_gymjot_cuff_DeviceMode mode;
    float fps;
} com_gymjot_cuff_BootEvent;

typedef struct _com_gymjot_cuff_StatusEvent {
    char status_label[33];
    com_gymjot_cuff_DeviceMode mode;
    float fps;
    bool test_mode;
} com_gymjot_cuff_StatusEvent;

typedef struct _com_gymjot_cuff_TagEvent {
    uint32_t tag_id;
    bool from_test_mode;
} com_gymjot_cuff_TagEvent;

typedef struct _com_gymjot_cuff_ExerciseRequestEvent {
    uint32_t tag_id;
} com_gymjot_cuff_ExerciseRequestEvent;

typedef struct _com_gymjot_cuff_ExerciseBroadcastEvent {
    uint32_t exercise_id;
    char name[65];
    bool has_metadata;
    com_gymjot_cuff_ExerciseMetadata metadata;
    bool from_test_mode;
} com_gymjot_cuff_ExerciseBroadcastEvent;

typedef struct _com_gymjot_cuff_ExerciseReadyEvent {
    uint32_t exercise_id;
} com_gymjot_cuff_ExerciseReadyEvent;

typedef struct _com_gymjot_cuff_ScanEvent {
    uint32_t tag_id;
    float distance_cm;
    com_gymjot_cuff_DeviceMode mode;
    float fps;
    bool has_exercise_name;
    char exercise_name[65];
} com_gymjot_cuff_ScanEvent;

typedef struct _com_gymjot_cuff_RepEvent {
    uint32_t tag_id;
    uint32_t rep_count;
    bool has_exercise_name;
    char exercise_name[65];
} com_gymjot_cuff_RepEvent;

typedef struct _com_gymjot_cuff_SnapshotEvent {
    uint64_t device_id;
    char name[65];
    com_gymjot_cuff_DeviceMode mode;
    bool test_mode;
    float target_fps;
    float loiter_fps;
    float min_travel_cm;
    uint32_t max_rep_idle_ms;
    bool camera_ready;
    bool ota_in_progress;
    uint32_t active_tag_id;
    /* Connection telemetry (added for BLE diagnostics) */
    bool ble_connected;
    uint32_t ble_mtu; /* Current MTU in bytes */
    uint32_t conn_interval_ms; /* Connection interval in milliseconds (x100 for precision) */
    uint32_t conn_latency; /* Slave latency */
    uint32_t supervision_timeout_ms; /* Supervision timeout in milliseconds */
    uint32_t last_disconnect_reason; /* Last HCI disconnect reason code */
    uint32_t bonded_count; /* Number of bonded devices */
} com_gymjot_cuff_SnapshotEvent;

typedef struct _com_gymjot_cuff_OtaStatusEvent {
    com_gymjot_cuff_OtaPhase phase;
    char message[97];
    uint32_t bytes_transferred;
    uint32_t total_bytes;
    bool success;
} com_gymjot_cuff_OtaStatusEvent;

typedef struct _com_gymjot_cuff_PhotoMetaEvent {
    uint32_t session_id;
    uint32_t total_bytes;
    uint32_t width;
    uint32_t height;
    char mime_type[33];
} com_gymjot_cuff_PhotoMetaEvent;

typedef PB_BYTES_ARRAY_T(200) com_gymjot_cuff_PhotoChunkEvent_data_t;
typedef struct _com_gymjot_cuff_PhotoChunkEvent {
    uint32_t session_id;
    uint32_t offset;
    com_gymjot_cuff_PhotoChunkEvent_data_t data;
    bool final_chunk;
} com_gymjot_cuff_PhotoChunkEvent;

typedef struct _com_gymjot_cuff_PowerEvent {
    char state[33];
} com_gymjot_cuff_PowerEvent;

typedef PB_BYTES_ARRAY_T(200) com_gymjot_cuff_VideoFrameEvent_data_t;
typedef struct _com_gymjot_cuff_VideoFrameEvent {
    uint32_t session_id;
    uint32_t frame_number;
    uint32_t total_bytes;
    uint32_t offset;
    com_gymjot_cuff_VideoFrameEvent_data_t data;
    bool final_chunk;
    uint32_t width;
    uint32_t height;
} com_gymjot_cuff_VideoFrameEvent;

typedef struct _com_gymjot_cuff_AprilTagDetectedEvent {
    uint32_t tag_id;
    float distance_cm;
    float decision_margin;
    /* Corner positions (normalized 0-1) */
    float corner_x1;
    float corner_y1;
    float corner_x2;
    float corner_y2;
    float corner_x3;
    float corner_y3;
    float corner_x4;
    float corner_y4;
} com_gymjot_cuff_AprilTagDetectedEvent;

typedef struct _com_gymjot_cuff_MotionDetectedEvent {
    float motion_score; /* 0-100, percentage of pixels changed */
    uint32_t pixels_changed;
    uint32_t total_pixels;
} com_gymjot_cuff_MotionDetectedEvent;

typedef struct _com_gymjot_cuff_DeviceEvent {
    uint64_t timestamp_ms;
    pb_size_t which_event;
    union {
        com_gymjot_cuff_BootEvent boot;
        com_gymjot_cuff_StatusEvent status;
        com_gymjot_cuff_TagEvent tag;
        com_gymjot_cuff_ExerciseRequestEvent exercise_request;
        com_gymjot_cuff_ExerciseBroadcastEvent exercise_broadcast;
        com_gymjot_cuff_ScanEvent scan;
        com_gymjot_cuff_RepEvent rep;
        com_gymjot_cuff_ExerciseReadyEvent exercise_ready;
        com_gymjot_cuff_SnapshotEvent snapshot;
        com_gymjot_cuff_OtaStatusEvent ota_status;
        com_gymjot_cuff_PowerEvent power_event;
        com_gymjot_cuff_PhotoMetaEvent photo_meta;
        com_gymjot_cuff_PhotoChunkEvent photo_chunk;
        com_gymjot_cuff_VideoFrameEvent video_frame;
        com_gymjot_cuff_AprilTagDetectedEvent apriltag_detected;
        com_gymjot_cuff_MotionDetectedEvent motion_detected;
    } event;
} com_gymjot_cuff_DeviceEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _com_gymjot_cuff_DeviceMode_MIN com_gymjot_cuff_DeviceMode_DEVICE_MODE_IDLE
#define _com_gymjot_cuff_DeviceMode_MAX com_gymjot_cuff_DeviceMode_DEVICE_MODE_LOITER
#define _com_gymjot_cuff_DeviceMode_ARRAYSIZE ((com_gymjot_cuff_DeviceMode)(com_gymjot_cuff_DeviceMode_DEVICE_MODE_LOITER+1))

#define _com_gymjot_cuff_OtaPhase_MIN com_gymjot_cuff_OtaPhase_OTA_PHASE_IDLE
#define _com_gymjot_cuff_OtaPhase_MAX com_gymjot_cuff_OtaPhase_OTA_PHASE_ERROR
#define _com_gymjot_cuff_OtaPhase_ARRAYSIZE ((com_gymjot_cuff_OtaPhase)(com_gymjot_cuff_OtaPhase_OTA_PHASE_ERROR+1))




















#define com_gymjot_cuff_BootEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode

#define com_gymjot_cuff_StatusEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode





#define com_gymjot_cuff_ScanEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode


#define com_gymjot_cuff_SnapshotEvent_mode_ENUMTYPE com_gymjot_cuff_DeviceMode

#define com_gymjot_cuff_OtaStatusEvent_phase_ENUMTYPE com_gymjot_cuff_OtaPhase








/* Initializer values for message structs */
#define com_gymjot_cuff_MetadataEntry_init_default {"", ""}
#define com_gymjot_cuff_ExerciseMetadata_init_default {0, {com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default, com_gymjot_cuff_MetadataEntry_init_default}}
#define com_gymjot_cuff_DeviceCommand_init_default {0, 0, {com_gymjot_cuff_SetTestModeCommand_init_default}}
#define com_gymjot_cuff_SetTestModeCommand_init_default {0}
#define com_gymjot_cuff_SetTargetFpsCommand_init_default {0}
#define com_gymjot_cuff_ExerciseUpdateCommand_init_default {0, "", false, com_gymjot_cuff_ExerciseMetadata_init_default, 0, 0, 0, 0}
#define com_gymjot_cuff_ResetRepsCommand_init_default {0}
#define com_gymjot_cuff_PowerCommand_init_default {0}
#define com_gymjot_cuff_FactoryResetCommand_init_default {0}
#define com_gymjot_cuff_ClearBondsCommand_init_default {0}
#define com_gymjot_cuff_SnapshotRequestCommand_init_default {0}
#define com_gymjot_cuff_TakePhotoCommand_init_default {0}
#define com_gymjot_cuff_UpdateDeviceConfigCommand_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define com_gymjot_cuff_OtaBeginCommand_init_default {0, 0, "", {{NULL}, NULL}}
#define com_gymjot_cuff_OtaChunkCommand_init_default {0, {{NULL}, NULL}}
#define com_gymjot_cuff_OtaCompleteCommand_init_default {0}
#define com_gymjot_cuff_StartVideoCommand_init_default {0, 0, 0}
#define com_gymjot_cuff_StopVideoCommand_init_default {0}
#define com_gymjot_cuff_DeviceEvent_init_default {0, 0, {com_gymjot_cuff_BootEvent_init_default}}
#define com_gymjot_cuff_BootEvent_init_default   {0, _com_gymjot_cuff_DeviceMode_MIN, 0}
#define com_gymjot_cuff_StatusEvent_init_default {"", _com_gymjot_cuff_DeviceMode_MIN, 0, 0}
#define com_gymjot_cuff_TagEvent_init_default    {0, 0}
#define com_gymjot_cuff_ExerciseRequestEvent_init_default {0}
#define com_gymjot_cuff_ExerciseBroadcastEvent_init_default {0, "", false, com_gymjot_cuff_ExerciseMetadata_init_default, 0}
#define com_gymjot_cuff_ExerciseReadyEvent_init_default {0}
#define com_gymjot_cuff_ScanEvent_init_default   {0, 0, _com_gymjot_cuff_DeviceMode_MIN, 0, 0, ""}
#define com_gymjot_cuff_RepEvent_init_default    {0, 0, 0, ""}
#define com_gymjot_cuff_SnapshotEvent_init_default {0, "", _com_gymjot_cuff_DeviceMode_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define com_gymjot_cuff_OtaStatusEvent_init_default {_com_gymjot_cuff_OtaPhase_MIN, "", 0, 0, 0}
#define com_gymjot_cuff_PhotoMetaEvent_init_default {0, 0, 0, 0, ""}
#define com_gymjot_cuff_PhotoChunkEvent_init_default {0, 0, {0, {0}}, 0}
#define com_gymjot_cuff_PowerEvent_init_default  {""}
#define com_gymjot_cuff_VideoFrameEvent_init_default {0, 0, 0, 0, {0, {0}}, 0, 0, 0}
#define com_gymjot_cuff_AprilTagDetectedEvent_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define com_gymjot_cuff_MotionDetectedEvent_init_default {0, 0, 0}
#define com_gymjot_cuff_MetadataEntry_init_zero  {"", ""}
#define com_gymjot_cuff_ExerciseMetadata_init_zero {0, {com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero, com_gymjot_cuff_MetadataEntry_init_zero}}
#define com_gymjot_cuff_DeviceCommand_init_zero  {0, 0, {com_gymjot_cuff_SetTestModeCommand_init_zero}}
#define com_gymjot_cuff_SetTestModeCommand_init_zero {0}
#define com_gymjot_cuff_SetTargetFpsCommand_init_zero {0}
#define com_gymjot_cuff_ExerciseUpdateCommand_init_zero {0, "", false, com_gymjot_cuff_ExerciseMetadata_init_zero, 0, 0, 0, 0}
#define com_gymjot_cuff_ResetRepsCommand_init_zero {0}
#define com_gymjot_cuff_PowerCommand_init_zero   {0}
#define com_gymjot_cuff_FactoryResetCommand_init_zero {0}
#define com_gymjot_cuff_ClearBondsCommand_init_zero {0}
#define com_gymjot_cuff_SnapshotRequestCommand_init_zero {0}
#define com_gymjot_cuff_TakePhotoCommand_init_zero {0}
#define com_gymjot_cuff_UpdateDeviceConfigCommand_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define com_gymjot_cuff_OtaBeginCommand_init_zero {0, 0, "", {{NULL}, NULL}}
#define com_gymjot_cuff_OtaChunkCommand_init_zero {0, {{NULL}, NULL}}
#define com_gymjot_cuff_OtaCompleteCommand_init_zero {0}
#define com_gymjot_cuff_StartVideoCommand_init_zero {0, 0, 0}
#define com_gymjot_cuff_StopVideoCommand_init_zero {0}
#define com_gymjot_cuff_DeviceEvent_init_zero    {0, 0, {com_gymjot_cuff_BootEvent_init_zero}}
#define com_gymjot_cuff_BootEvent_init_zero      {0, _com_gymjot_cuff_DeviceMode_MIN, 0}
#define com_gymjot_cuff_StatusEvent_init_zero    {"", _com_gymjot_cuff_DeviceMode_MIN, 0, 0}
#define com_gymjot_cuff_TagEvent_init_zero       {0, 0}
#define com_gymjot_cuff_ExerciseRequestEvent_init_zero {0}
#define com_gymjot_cuff_ExerciseBroadcastEvent_init_zero {0, "", false, com_gymjot_cuff_ExerciseMetadata_init_zero, 0}
#define com_gymjot_cuff_ExerciseReadyEvent_init_zero {0}
#define com_gymjot_cuff_ScanEvent_init_zero      {0, 0, _com_gymjot_cuff_DeviceMode_MIN, 0, 0, ""}
#define com_gymjot_cuff_RepEvent_init_zero       {0, 0, 0, ""}
#define com_gymjot_cuff_SnapshotEvent_init_zero  {0, "", _com_gymjot_cuff_DeviceMode_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define com_gymjot_cuff_OtaStatusEvent_init_zero {_com_gymjot_cuff_OtaPhase_MIN, "", 0, 0, 0}
#define com_gymjot_cuff_PhotoMetaEvent_init_zero {0, 0, 0, 0, ""}
#define com_gymjot_cuff_PhotoChunkEvent_init_zero {0, 0, {0, {0}}, 0}
#define com_gymjot_cuff_PowerEvent_init_zero     {""}
#define com_gymjot_cuff_VideoFrameEvent_init_zero {0, 0, 0, 0, {0, {0}}, 0, 0, 0}
#define com_gymjot_cuff_AprilTagDetectedEvent_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define com_gymjot_cuff_MotionDetectedEvent_init_zero {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define com_gymjot_cuff_MetadataEntry_key_tag    1
#define com_gymjot_cuff_MetadataEntry_value_tag  2
#define com_gymjot_cuff_ExerciseMetadata_entries_tag 1
#define com_gymjot_cuff_SetTestModeCommand_enabled_tag 1
#define com_gymjot_cuff_SetTargetFpsCommand_fps_tag 1
#define com_gymjot_cuff_ExerciseUpdateCommand_exercise_id_tag 1
#define com_gymjot_cuff_ExerciseUpdateCommand_name_tag 2
#define com_gymjot_cuff_ExerciseUpdateCommand_metadata_tag 3
#define com_gymjot_cuff_ExerciseUpdateCommand_set_min_travel_cm_tag 4
#define com_gymjot_cuff_ExerciseUpdateCommand_min_travel_cm_tag 5
#define com_gymjot_cuff_ExerciseUpdateCommand_set_fps_tag 6
#define com_gymjot_cuff_ExerciseUpdateCommand_fps_tag 7
#define com_gymjot_cuff_PowerCommand_shutdown_tag 1
#define com_gymjot_cuff_FactoryResetCommand_confirm_tag 1
#define com_gymjot_cuff_ClearBondsCommand_confirm_tag 1
#define com_gymjot_cuff_TakePhotoCommand_high_resolution_tag 1
#define com_gymjot_cuff_UpdateDeviceConfigCommand_set_target_fps_tag 1
#define com_gymjot_cuff_UpdateDeviceConfigCommand_target_fps_tag 2
#define com_gymjot_cuff_UpdateDeviceConfigCommand_set_loiter_fps_tag 3
#define com_gymjot_cuff_UpdateDeviceConfigCommand_loiter_fps_tag 4
#define com_gymjot_cuff_UpdateDeviceConfigCommand_set_min_travel_cm_tag 5
#define com_gymjot_cuff_UpdateDeviceConfigCommand_min_travel_cm_tag 6
#define com_gymjot_cuff_UpdateDeviceConfigCommand_set_max_rep_idle_ms_tag 7
#define com_gymjot_cuff_UpdateDeviceConfigCommand_max_rep_idle_ms_tag 8
#define com_gymjot_cuff_OtaBeginCommand_total_size_tag 1
#define com_gymjot_cuff_OtaBeginCommand_chunk_size_tag 2
#define com_gymjot_cuff_OtaBeginCommand_version_tag 3
#define com_gymjot_cuff_OtaBeginCommand_sha256_tag 4
#define com_gymjot_cuff_OtaChunkCommand_offset_tag 1
#define com_gymjot_cuff_OtaChunkCommand_data_tag 2
#define com_gymjot_cuff_OtaCompleteCommand_apply_tag 1
#define com_gymjot_cuff_StartVideoCommand_fps_tag 1
#define com_gymjot_cuff_StartVideoCommand_enable_apriltag_detection_tag 2
#define com_gymjot_cuff_StartVideoCommand_enable_motion_detection_tag 3
#define com_gymjot_cuff_DeviceCommand_timestamp_ms_tag 1
#define com_gymjot_cuff_DeviceCommand_set_test_mode_tag 10
#define com_gymjot_cuff_DeviceCommand_set_target_fps_tag 11
#define com_gymjot_cuff_DeviceCommand_exercise_update_tag 12
#define com_gymjot_cuff_DeviceCommand_reset_reps_tag 13
#define com_gymjot_cuff_DeviceCommand_power_tag  14
#define com_gymjot_cuff_DeviceCommand_factory_reset_tag 15
#define com_gymjot_cuff_DeviceCommand_snapshot_request_tag 16
#define com_gymjot_cuff_DeviceCommand_update_device_config_tag 17
#define com_gymjot_cuff_DeviceCommand_ota_begin_tag 18
#define com_gymjot_cuff_DeviceCommand_ota_chunk_tag 19
#define com_gymjot_cuff_DeviceCommand_ota_complete_tag 20
#define com_gymjot_cuff_DeviceCommand_clear_bonds_tag 21
#define com_gymjot_cuff_DeviceCommand_take_photo_tag 22
#define com_gymjot_cuff_DeviceCommand_start_video_tag 23
#define com_gymjot_cuff_DeviceCommand_stop_video_tag 24
#define com_gymjot_cuff_BootEvent_test_mode_tag  1
#define com_gymjot_cuff_BootEvent_mode_tag       2
#define com_gymjot_cuff_BootEvent_fps_tag        3
#define com_gymjot_cuff_StatusEvent_status_label_tag 1
#define com_gymjot_cuff_StatusEvent_mode_tag     2
#define com_gymjot_cuff_StatusEvent_fps_tag      3
#define com_gymjot_cuff_StatusEvent_test_mode_tag 4
#define com_gymjot_cuff_TagEvent_tag_id_tag      1
#define com_gymjot_cuff_TagEvent_from_test_mode_tag 2
#define com_gymjot_cuff_ExerciseRequestEvent_tag_id_tag 1
#define com_gymjot_cuff_ExerciseBroadcastEvent_exercise_id_tag 1
#define com_gymjot_cuff_ExerciseBroadcastEvent_name_tag 2
#define com_gymjot_cuff_ExerciseBroadcastEvent_metadata_tag 3
#define com_gymjot_cuff_ExerciseBroadcastEvent_from_test_mode_tag 4
#define com_gymjot_cuff_ExerciseReadyEvent_exercise_id_tag 1
#define com_gymjot_cuff_ScanEvent_tag_id_tag     1
#define com_gymjot_cuff_ScanEvent_distance_cm_tag 2
#define com_gymjot_cuff_ScanEvent_mode_tag       3
#define com_gymjot_cuff_ScanEvent_fps_tag        4
#define com_gymjot_cuff_ScanEvent_has_exercise_name_tag 5
#define com_gymjot_cuff_ScanEvent_exercise_name_tag 6
#define com_gymjot_cuff_RepEvent_tag_id_tag      1
#define com_gymjot_cuff_RepEvent_rep_count_tag   2
#define com_gymjot_cuff_RepEvent_has_exercise_name_tag 3
#define com_gymjot_cuff_RepEvent_exercise_name_tag 4
#define com_gymjot_cuff_SnapshotEvent_device_id_tag 1
#define com_gymjot_cuff_SnapshotEvent_name_tag   2
#define com_gymjot_cuff_SnapshotEvent_mode_tag   3
#define com_gymjot_cuff_SnapshotEvent_test_mode_tag 4
#define com_gymjot_cuff_SnapshotEvent_target_fps_tag 5
#define com_gymjot_cuff_SnapshotEvent_loiter_fps_tag 6
#define com_gymjot_cuff_SnapshotEvent_min_travel_cm_tag 7
#define com_gymjot_cuff_SnapshotEvent_max_rep_idle_ms_tag 8
#define com_gymjot_cuff_SnapshotEvent_camera_ready_tag 9
#define com_gymjot_cuff_SnapshotEvent_ota_in_progress_tag 10
#define com_gymjot_cuff_SnapshotEvent_active_tag_id_tag 11
#define com_gymjot_cuff_SnapshotEvent_ble_connected_tag 12
#define com_gymjot_cuff_SnapshotEvent_ble_mtu_tag 13
#define com_gymjot_cuff_SnapshotEvent_conn_interval_ms_tag 14
#define com_gymjot_cuff_SnapshotEvent_conn_latency_tag 15
#define com_gymjot_cuff_SnapshotEvent_supervision_timeout_ms_tag 16
#define com_gymjot_cuff_SnapshotEvent_last_disconnect_reason_tag 17
#define com_gymjot_cuff_SnapshotEvent_bonded_count_tag 18
#define com_gymjot_cuff_OtaStatusEvent_phase_tag 1
#define com_gymjot_cuff_OtaStatusEvent_message_tag 2
#define com_gymjot_cuff_OtaStatusEvent_bytes_transferred_tag 3
#define com_gymjot_cuff_OtaStatusEvent_total_bytes_tag 4
#define com_gymjot_cuff_OtaStatusEvent_success_tag 5
#define com_gymjot_cuff_PhotoMetaEvent_session_id_tag 1
#define com_gymjot_cuff_PhotoMetaEvent_total_bytes_tag 2
#define com_gymjot_cuff_PhotoMetaEvent_width_tag 3
#define com_gymjot_cuff_PhotoMetaEvent_height_tag 4
#define com_gymjot_cuff_PhotoMetaEvent_mime_type_tag 5
#define com_gymjot_cuff_PhotoChunkEvent_session_id_tag 1
#define com_gymjot_cuff_PhotoChunkEvent_offset_tag 2
#define com_gymjot_cuff_PhotoChunkEvent_data_tag 3
#define com_gymjot_cuff_PhotoChunkEvent_final_chunk_tag 4
#define com_gymjot_cuff_PowerEvent_state_tag     1
#define com_gymjot_cuff_VideoFrameEvent_session_id_tag 1
#define com_gymjot_cuff_VideoFrameEvent_frame_number_tag 2
#define com_gymjot_cuff_VideoFrameEvent_total_bytes_tag 3
#define com_gymjot_cuff_VideoFrameEvent_offset_tag 4
#define com_gymjot_cuff_VideoFrameEvent_data_tag 5
#define com_gymjot_cuff_VideoFrameEvent_final_chunk_tag 6
#define com_gymjot_cuff_VideoFrameEvent_width_tag 7
#define com_gymjot_cuff_VideoFrameEvent_height_tag 8
#define com_gymjot_cuff_AprilTagDetectedEvent_tag_id_tag 1
#define com_gymjot_cuff_AprilTagDetectedEvent_distance_cm_tag 2
#define com_gymjot_cuff_AprilTagDetectedEvent_decision_margin_tag 3
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_x1_tag 4
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_y1_tag 5
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_x2_tag 6
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_y2_tag 7
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_x3_tag 8
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_y3_tag 9
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_x4_tag 10
#define com_gymjot_cuff_AprilTagDetectedEvent_corner_y4_tag 11
#define com_gymjot_cuff_MotionDetectedEvent_motion_score_tag 1
#define com_gymjot_cuff_MotionDetectedEvent_pixels_changed_tag 2
#define com_gymjot_cuff_MotionDetectedEvent_total_pixels_tag 3
#define com_gymjot_cuff_DeviceEvent_timestamp_ms_tag 1
#define com_gymjot_cuff_DeviceEvent_boot_tag     10
#define com_gymjot_cuff_DeviceEvent_status_tag   11
#define com_gymjot_cuff_DeviceEvent_tag_tag      12
#define com_gymjot_cuff_DeviceEvent_exercise_request_tag 13
#define com_gymjot_cuff_DeviceEvent_exercise_broadcast_tag 14
#define com_gymjot_cuff_DeviceEvent_scan_tag     15
#define com_gymjot_cuff_DeviceEvent_rep_tag      16
#define com_gymjot_cuff_DeviceEvent_exercise_ready_tag 17
#define com_gymjot_cuff_DeviceEvent_snapshot_tag 18
#define com_gymjot_cuff_DeviceEvent_ota_status_tag 19
#define com_gymjot_cuff_DeviceEvent_power_event_tag 20
#define com_gymjot_cuff_DeviceEvent_photo_meta_tag 21
#define com_gymjot_cuff_DeviceEvent_photo_chunk_tag 22
#define com_gymjot_cuff_DeviceEvent_video_frame_tag 23
#define com_gymjot_cuff_DeviceEvent_apriltag_detected_tag 24
#define com_gymjot_cuff_DeviceEvent_motion_detected_tag 25

/* Struct field encoding specification for nanopb */
#define com_gymjot_cuff_MetadataEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define com_gymjot_cuff_MetadataEntry_CALLBACK NULL
#define com_gymjot_cuff_MetadataEntry_DEFAULT NULL

#define com_gymjot_cuff_ExerciseMetadata_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  entries,           1)
#define com_gymjot_cuff_ExerciseMetadata_CALLBACK NULL
#define com_gymjot_cuff_ExerciseMetadata_DEFAULT NULL
#define com_gymjot_cuff_ExerciseMetadata_entries_MSGTYPE com_gymjot_cuff_MetadataEntry

#define com_gymjot_cuff_DeviceCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_test_mode,command.set_test_mode),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_target_fps,command.set_target_fps),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,exercise_update,command.exercise_update),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,reset_reps,command.reset_reps),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,power,command.power),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,factory_reset,command.factory_reset),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,snapshot_request,command.snapshot_request),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,update_device_config,command.update_device_config),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ota_begin,command.ota_begin),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ota_chunk,command.ota_chunk),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,ota_complete,command.ota_complete),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,clear_bonds,command.clear_bonds),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,take_photo,command.take_photo),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,start_video,command.start_video),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,stop_video,command.stop_video),  24)
#define com_gymjot_cuff_DeviceCommand_CALLBACK NULL
#define com_gymjot_cuff_DeviceCommand_DEFAULT NULL
#define com_gymjot_cuff_DeviceCommand_command_set_test_mode_MSGTYPE com_gymjot_cuff_SetTestModeCommand
#define com_gymjot_cuff_DeviceCommand_command_set_target_fps_MSGTYPE com_gymjot_cuff_SetTargetFpsCommand
#define com_gymjot_cuff_DeviceCommand_command_exercise_update_MSGTYPE com_gymjot_cuff_ExerciseUpdateCommand
#define com_gymjot_cuff_DeviceCommand_command_reset_reps_MSGTYPE com_gymjot_cuff_ResetRepsCommand
#define com_gymjot_cuff_DeviceCommand_command_power_MSGTYPE com_gymjot_cuff_PowerCommand
#define com_gymjot_cuff_DeviceCommand_command_factory_reset_MSGTYPE com_gymjot_cuff_FactoryResetCommand
#define com_gymjot_cuff_DeviceCommand_command_snapshot_request_MSGTYPE com_gymjot_cuff_SnapshotRequestCommand
#define com_gymjot_cuff_DeviceCommand_command_update_device_config_MSGTYPE com_gymjot_cuff_UpdateDeviceConfigCommand
#define com_gymjot_cuff_DeviceCommand_command_ota_begin_MSGTYPE com_gymjot_cuff_OtaBeginCommand
#define com_gymjot_cuff_DeviceCommand_command_ota_chunk_MSGTYPE com_gymjot_cuff_OtaChunkCommand
#define com_gymjot_cuff_DeviceCommand_command_ota_complete_MSGTYPE com_gymjot_cuff_OtaCompleteCommand
#define com_gymjot_cuff_DeviceCommand_command_clear_bonds_MSGTYPE com_gymjot_cuff_ClearBondsCommand
#define com_gymjot_cuff_DeviceCommand_command_take_photo_MSGTYPE com_gymjot_cuff_TakePhotoCommand
#define com_gymjot_cuff_DeviceCommand_command_start_video_MSGTYPE com_gymjot_cuff_StartVideoCommand
#define com_gymjot_cuff_DeviceCommand_command_stop_video_MSGTYPE com_gymjot_cuff_StopVideoCommand

#define com_gymjot_cuff_SetTestModeCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1)
#define com_gymjot_cuff_SetTestModeCommand_CALLBACK NULL
#define com_gymjot_cuff_SetTestModeCommand_DEFAULT NULL

#define com_gymjot_cuff_SetTargetFpsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               1)
#define com_gymjot_cuff_SetTargetFpsCommand_CALLBACK NULL
#define com_gymjot_cuff_SetTargetFpsCommand_DEFAULT NULL

#define com_gymjot_cuff_ExerciseUpdateCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   exercise_id,       1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          3) \
X(a, STATIC,   SINGULAR, BOOL,     set_min_travel_cm,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    min_travel_cm,     5) \
X(a, STATIC,   SINGULAR, BOOL,     set_fps,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               7)
#define com_gymjot_cuff_ExerciseUpdateCommand_CALLBACK NULL
#define com_gymjot_cuff_ExerciseUpdateCommand_DEFAULT NULL
#define com_gymjot_cuff_ExerciseUpdateCommand_metadata_MSGTYPE com_gymjot_cuff_ExerciseMetadata

#define com_gymjot_cuff_ResetRepsCommand_FIELDLIST(X, a) \

#define com_gymjot_cuff_ResetRepsCommand_CALLBACK NULL
#define com_gymjot_cuff_ResetRepsCommand_DEFAULT NULL

#define com_gymjot_cuff_PowerCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     shutdown,          1)
#define com_gymjot_cuff_PowerCommand_CALLBACK NULL
#define com_gymjot_cuff_PowerCommand_DEFAULT NULL

#define com_gymjot_cuff_FactoryResetCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     confirm,           1)
#define com_gymjot_cuff_FactoryResetCommand_CALLBACK NULL
#define com_gymjot_cuff_FactoryResetCommand_DEFAULT NULL

#define com_gymjot_cuff_ClearBondsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     confirm,           1)
#define com_gymjot_cuff_ClearBondsCommand_CALLBACK NULL
#define com_gymjot_cuff_ClearBondsCommand_DEFAULT NULL

#define com_gymjot_cuff_SnapshotRequestCommand_FIELDLIST(X, a) \

#define com_gymjot_cuff_SnapshotRequestCommand_CALLBACK NULL
#define com_gymjot_cuff_SnapshotRequestCommand_DEFAULT NULL

#define com_gymjot_cuff_TakePhotoCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     high_resolution,   1)
#define com_gymjot_cuff_TakePhotoCommand_CALLBACK NULL
#define com_gymjot_cuff_TakePhotoCommand_DEFAULT NULL

#define com_gymjot_cuff_UpdateDeviceConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     set_target_fps,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    target_fps,        2) \
X(a, STATIC,   SINGULAR, BOOL,     set_loiter_fps,    3) \
X(a, STATIC,   SINGULAR, FLOAT,    loiter_fps,        4) \
X(a, STATIC,   SINGULAR, BOOL,     set_min_travel_cm,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    min_travel_cm,     6) \
X(a, STATIC,   SINGULAR, BOOL,     set_max_rep_idle_ms,   7) \
X(a, STATIC,   SINGULAR, UINT32,   max_rep_idle_ms,   8)
#define com_gymjot_cuff_UpdateDeviceConfigCommand_CALLBACK NULL
#define com_gymjot_cuff_UpdateDeviceConfigCommand_DEFAULT NULL

#define com_gymjot_cuff_OtaBeginCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_size,        1) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size,        2) \
X(a, STATIC,   SINGULAR, STRING,   version,           3) \
X(a, CALLBACK, SINGULAR, BYTES,    sha256,            4)
#define com_gymjot_cuff_OtaBeginCommand_CALLBACK pb_default_field_callback
#define com_gymjot_cuff_OtaBeginCommand_DEFAULT NULL

#define com_gymjot_cuff_OtaChunkCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define com_gymjot_cuff_OtaChunkCommand_CALLBACK pb_default_field_callback
#define com_gymjot_cuff_OtaChunkCommand_DEFAULT NULL

#define com_gymjot_cuff_OtaCompleteCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     apply,             1)
#define com_gymjot_cuff_OtaCompleteCommand_CALLBACK NULL
#define com_gymjot_cuff_OtaCompleteCommand_DEFAULT NULL

#define com_gymjot_cuff_StartVideoCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               1) \
X(a, STATIC,   SINGULAR, BOOL,     enable_apriltag_detection,   2) \
X(a, STATIC,   SINGULAR, BOOL,     enable_motion_detection,   3)
#define com_gymjot_cuff_StartVideoCommand_CALLBACK NULL
#define com_gymjot_cuff_StartVideoCommand_DEFAULT NULL

#define com_gymjot_cuff_StopVideoCommand_FIELDLIST(X, a) \

#define com_gymjot_cuff_StopVideoCommand_CALLBACK NULL
#define com_gymjot_cuff_StopVideoCommand_DEFAULT NULL

#define com_gymjot_cuff_DeviceEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,boot,event.boot),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,status,event.status),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,tag,event.tag),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,exercise_request,event.exercise_request),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,exercise_broadcast,event.exercise_broadcast),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,scan,event.scan),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,rep,event.rep),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,exercise_ready,event.exercise_ready),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,snapshot,event.snapshot),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,ota_status,event.ota_status),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,power_event,event.power_event),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,photo_meta,event.photo_meta),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,photo_chunk,event.photo_chunk),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,video_frame,event.video_frame),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,apriltag_detected,event.apriltag_detected),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,motion_detected,event.motion_detected),  25)
#define com_gymjot_cuff_DeviceEvent_CALLBACK NULL
#define com_gymjot_cuff_DeviceEvent_DEFAULT NULL
#define com_gymjot_cuff_DeviceEvent_event_boot_MSGTYPE com_gymjot_cuff_BootEvent
#define com_gymjot_cuff_DeviceEvent_event_status_MSGTYPE com_gymjot_cuff_StatusEvent
#define com_gymjot_cuff_DeviceEvent_event_tag_MSGTYPE com_gymjot_cuff_TagEvent
#define com_gymjot_cuff_DeviceEvent_event_exercise_request_MSGTYPE com_gymjot_cuff_ExerciseRequestEvent
#define com_gymjot_cuff_DeviceEvent_event_exercise_broadcast_MSGTYPE com_gymjot_cuff_ExerciseBroadcastEvent
#define com_gymjot_cuff_DeviceEvent_event_scan_MSGTYPE com_gymjot_cuff_ScanEvent
#define com_gymjot_cuff_DeviceEvent_event_rep_MSGTYPE com_gymjot_cuff_RepEvent
#define com_gymjot_cuff_DeviceEvent_event_exercise_ready_MSGTYPE com_gymjot_cuff_ExerciseReadyEvent
#define com_gymjot_cuff_DeviceEvent_event_snapshot_MSGTYPE com_gymjot_cuff_SnapshotEvent
#define com_gymjot_cuff_DeviceEvent_event_ota_status_MSGTYPE com_gymjot_cuff_OtaStatusEvent
#define com_gymjot_cuff_DeviceEvent_event_power_event_MSGTYPE com_gymjot_cuff_PowerEvent
#define com_gymjot_cuff_DeviceEvent_event_photo_meta_MSGTYPE com_gymjot_cuff_PhotoMetaEvent
#define com_gymjot_cuff_DeviceEvent_event_photo_chunk_MSGTYPE com_gymjot_cuff_PhotoChunkEvent
#define com_gymjot_cuff_DeviceEvent_event_video_frame_MSGTYPE com_gymjot_cuff_VideoFrameEvent
#define com_gymjot_cuff_DeviceEvent_event_apriltag_detected_MSGTYPE com_gymjot_cuff_AprilTagDetectedEvent
#define com_gymjot_cuff_DeviceEvent_event_motion_detected_MSGTYPE com_gymjot_cuff_MotionDetectedEvent

#define com_gymjot_cuff_BootEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     test_mode,         1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               3)
#define com_gymjot_cuff_BootEvent_CALLBACK NULL
#define com_gymjot_cuff_BootEvent_DEFAULT NULL

#define com_gymjot_cuff_StatusEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   status_label,      1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               3) \
X(a, STATIC,   SINGULAR, BOOL,     test_mode,         4)
#define com_gymjot_cuff_StatusEvent_CALLBACK NULL
#define com_gymjot_cuff_StatusEvent_DEFAULT NULL

#define com_gymjot_cuff_TagEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, BOOL,     from_test_mode,    2)
#define com_gymjot_cuff_TagEvent_CALLBACK NULL
#define com_gymjot_cuff_TagEvent_DEFAULT NULL

#define com_gymjot_cuff_ExerciseRequestEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1)
#define com_gymjot_cuff_ExerciseRequestEvent_CALLBACK NULL
#define com_gymjot_cuff_ExerciseRequestEvent_DEFAULT NULL

#define com_gymjot_cuff_ExerciseBroadcastEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   exercise_id,       1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          3) \
X(a, STATIC,   SINGULAR, BOOL,     from_test_mode,    4)
#define com_gymjot_cuff_ExerciseBroadcastEvent_CALLBACK NULL
#define com_gymjot_cuff_ExerciseBroadcastEvent_DEFAULT NULL
#define com_gymjot_cuff_ExerciseBroadcastEvent_metadata_MSGTYPE com_gymjot_cuff_ExerciseMetadata

#define com_gymjot_cuff_ExerciseReadyEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   exercise_id,       1)
#define com_gymjot_cuff_ExerciseReadyEvent_CALLBACK NULL
#define com_gymjot_cuff_ExerciseReadyEvent_DEFAULT NULL

#define com_gymjot_cuff_ScanEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_cm,       2) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               4) \
X(a, STATIC,   SINGULAR, BOOL,     has_exercise_name,   5) \
X(a, STATIC,   SINGULAR, STRING,   exercise_name,     6)
#define com_gymjot_cuff_ScanEvent_CALLBACK NULL
#define com_gymjot_cuff_ScanEvent_DEFAULT NULL

#define com_gymjot_cuff_RepEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   rep_count,         2) \
X(a, STATIC,   SINGULAR, BOOL,     has_exercise_name,   3) \
X(a, STATIC,   SINGULAR, STRING,   exercise_name,     4)
#define com_gymjot_cuff_RepEvent_CALLBACK NULL
#define com_gymjot_cuff_RepEvent_DEFAULT NULL

#define com_gymjot_cuff_SnapshotEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   device_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              3) \
X(a, STATIC,   SINGULAR, BOOL,     test_mode,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    target_fps,        5) \
X(a, STATIC,   SINGULAR, FLOAT,    loiter_fps,        6) \
X(a, STATIC,   SINGULAR, FLOAT,    min_travel_cm,     7) \
X(a, STATIC,   SINGULAR, UINT32,   max_rep_idle_ms,   8) \
X(a, STATIC,   SINGULAR, BOOL,     camera_ready,      9) \
X(a, STATIC,   SINGULAR, BOOL,     ota_in_progress,  10) \
X(a, STATIC,   SINGULAR, UINT32,   active_tag_id,    11) \
X(a, STATIC,   SINGULAR, BOOL,     ble_connected,    12) \
X(a, STATIC,   SINGULAR, UINT32,   ble_mtu,          13) \
X(a, STATIC,   SINGULAR, UINT32,   conn_interval_ms,  14) \
X(a, STATIC,   SINGULAR, UINT32,   conn_latency,     15) \
X(a, STATIC,   SINGULAR, UINT32,   supervision_timeout_ms,  16) \
X(a, STATIC,   SINGULAR, UINT32,   last_disconnect_reason,  17) \
X(a, STATIC,   SINGULAR, UINT32,   bonded_count,     18)
#define com_gymjot_cuff_SnapshotEvent_CALLBACK NULL
#define com_gymjot_cuff_SnapshotEvent_DEFAULT NULL

#define com_gymjot_cuff_OtaStatusEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    phase,             1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_transferred,   3) \
X(a, STATIC,   SINGULAR, UINT32,   total_bytes,       4) \
X(a, STATIC,   SINGULAR, BOOL,     success,           5)
#define com_gymjot_cuff_OtaStatusEvent_CALLBACK NULL
#define com_gymjot_cuff_OtaStatusEvent_DEFAULT NULL

#define com_gymjot_cuff_PhotoMetaEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   total_bytes,       2) \
X(a, STATIC,   SINGULAR, UINT32,   width,             3) \
X(a, STATIC,   SINGULAR, UINT32,   height,            4) \
X(a, STATIC,   SINGULAR, STRING,   mime_type,         5)
#define com_gymjot_cuff_PhotoMetaEvent_CALLBACK NULL
#define com_gymjot_cuff_PhotoMetaEvent_DEFAULT NULL

#define com_gymjot_cuff_PhotoChunkEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3) \
X(a, STATIC,   SINGULAR, BOOL,     final_chunk,       4)
#define com_gymjot_cuff_PhotoChunkEvent_CALLBACK NULL
#define com_gymjot_cuff_PhotoChunkEvent_DEFAULT NULL

#define com_gymjot_cuff_PowerEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   state,             1)
#define com_gymjot_cuff_PowerEvent_CALLBACK NULL
#define com_gymjot_cuff_PowerEvent_DEFAULT NULL

#define com_gymjot_cuff_VideoFrameEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   session_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_number,      2) \
X(a, STATIC,   SINGULAR, UINT32,   total_bytes,       3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4) \
X(a, STATIC,   SINGULAR, BYTES,    data,              5) \
X(a, STATIC,   SINGULAR, BOOL,     final_chunk,       6) \
X(a, STATIC,   SINGULAR, UINT32,   width,             7) \
X(a, STATIC,   SINGULAR, UINT32,   height,            8)
#define com_gymjot_cuff_VideoFrameEvent_CALLBACK NULL
#define com_gymjot_cuff_VideoFrameEvent_DEFAULT NULL

#define com_gymjot_cuff_AprilTagDetectedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   tag_id,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    distance_cm,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    decision_margin,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_x1,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_y1,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_x2,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_y2,         7) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_x3,         8) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_y3,         9) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_x4,        10) \
X(a, STATIC,   SINGULAR, FLOAT,    corner_y4,        11)
#define com_gymjot_cuff_AprilTagDetectedEvent_CALLBACK NULL
#define com_gymjot_cuff_AprilTagDetectedEvent_DEFAULT NULL

#define com_gymjot_cuff_MotionDetectedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    motion_score,      1) \
X(a, STATIC,   SINGULAR, UINT32,   pixels_changed,    2) \
X(a, STATIC,   SINGULAR, UINT32,   total_pixels,      3)
#define com_gymjot_cuff_MotionDetectedEvent_CALLBACK NULL
#define com_gymjot_cuff_MotionDetectedEvent_DEFAULT NULL

extern const pb_msgdesc_t com_gymjot_cuff_MetadataEntry_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ExerciseMetadata_msg;
extern const pb_msgdesc_t com_gymjot_cuff_DeviceCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_SetTestModeCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_SetTargetFpsCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ExerciseUpdateCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ResetRepsCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_PowerCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_FactoryResetCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ClearBondsCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_SnapshotRequestCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_TakePhotoCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_UpdateDeviceConfigCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_OtaBeginCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_OtaChunkCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_OtaCompleteCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StartVideoCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StopVideoCommand_msg;
extern const pb_msgdesc_t com_gymjot_cuff_DeviceEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_BootEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_StatusEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_TagEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ExerciseRequestEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ExerciseBroadcastEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ExerciseReadyEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_ScanEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_RepEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_SnapshotEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_OtaStatusEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_PhotoMetaEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_PhotoChunkEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_PowerEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_VideoFrameEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_AprilTagDetectedEvent_msg;
extern const pb_msgdesc_t com_gymjot_cuff_MotionDetectedEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_gymjot_cuff_MetadataEntry_fields &com_gymjot_cuff_MetadataEntry_msg
#define com_gymjot_cuff_ExerciseMetadata_fields &com_gymjot_cuff_ExerciseMetadata_msg
#define com_gymjot_cuff_DeviceCommand_fields &com_gymjot_cuff_DeviceCommand_msg
#define com_gymjot_cuff_SetTestModeCommand_fields &com_gymjot_cuff_SetTestModeCommand_msg
#define com_gymjot_cuff_SetTargetFpsCommand_fields &com_gymjot_cuff_SetTargetFpsCommand_msg
#define com_gymjot_cuff_ExerciseUpdateCommand_fields &com_gymjot_cuff_ExerciseUpdateCommand_msg
#define com_gymjot_cuff_ResetRepsCommand_fields &com_gymjot_cuff_ResetRepsCommand_msg
#define com_gymjot_cuff_PowerCommand_fields &com_gymjot_cuff_PowerCommand_msg
#define com_gymjot_cuff_FactoryResetCommand_fields &com_gymjot_cuff_FactoryResetCommand_msg
#define com_gymjot_cuff_ClearBondsCommand_fields &com_gymjot_cuff_ClearBondsCommand_msg
#define com_gymjot_cuff_SnapshotRequestCommand_fields &com_gymjot_cuff_SnapshotRequestCommand_msg
#define com_gymjot_cuff_TakePhotoCommand_fields &com_gymjot_cuff_TakePhotoCommand_msg
#define com_gymjot_cuff_UpdateDeviceConfigCommand_fields &com_gymjot_cuff_UpdateDeviceConfigCommand_msg
#define com_gymjot_cuff_OtaBeginCommand_fields &com_gymjot_cuff_OtaBeginCommand_msg
#define com_gymjot_cuff_OtaChunkCommand_fields &com_gymjot_cuff_OtaChunkCommand_msg
#define com_gymjot_cuff_OtaCompleteCommand_fields &com_gymjot_cuff_OtaCompleteCommand_msg
#define com_gymjot_cuff_StartVideoCommand_fields &com_gymjot_cuff_StartVideoCommand_msg
#define com_gymjot_cuff_StopVideoCommand_fields &com_gymjot_cuff_StopVideoCommand_msg
#define com_gymjot_cuff_DeviceEvent_fields &com_gymjot_cuff_DeviceEvent_msg
#define com_gymjot_cuff_BootEvent_fields &com_gymjot_cuff_BootEvent_msg
#define com_gymjot_cuff_StatusEvent_fields &com_gymjot_cuff_StatusEvent_msg
#define com_gymjot_cuff_TagEvent_fields &com_gymjot_cuff_TagEvent_msg
#define com_gymjot_cuff_ExerciseRequestEvent_fields &com_gymjot_cuff_ExerciseRequestEvent_msg
#define com_gymjot_cuff_ExerciseBroadcastEvent_fields &com_gymjot_cuff_ExerciseBroadcastEvent_msg
#define com_gymjot_cuff_ExerciseReadyEvent_fields &com_gymjot_cuff_ExerciseReadyEvent_msg
#define com_gymjot_cuff_ScanEvent_fields &com_gymjot_cuff_ScanEvent_msg
#define com_gymjot_cuff_RepEvent_fields &com_gymjot_cuff_RepEvent_msg
#define com_gymjot_cuff_SnapshotEvent_fields &com_gymjot_cuff_SnapshotEvent_msg
#define com_gymjot_cuff_OtaStatusEvent_fields &com_gymjot_cuff_OtaStatusEvent_msg
#define com_gymjot_cuff_PhotoMetaEvent_fields &com_gymjot_cuff_PhotoMetaEvent_msg
#define com_gymjot_cuff_PhotoChunkEvent_fields &com_gymjot_cuff_PhotoChunkEvent_msg
#define com_gymjot_cuff_PowerEvent_fields &com_gymjot_cuff_PowerEvent_msg
#define com_gymjot_cuff_VideoFrameEvent_fields &com_gymjot_cuff_VideoFrameEvent_msg
#define com_gymjot_cuff_AprilTagDetectedEvent_fields &com_gymjot_cuff_AprilTagDetectedEvent_msg
#define com_gymjot_cuff_MotionDetectedEvent_fields &com_gymjot_cuff_MotionDetectedEvent_msg

/* Maximum encoded size of messages (where known) */
/* com_gymjot_cuff_DeviceCommand_size depends on runtime parameters */
/* com_gymjot_cuff_OtaBeginCommand_size depends on runtime parameters */
/* com_gymjot_cuff_OtaChunkCommand_size depends on runtime parameters */
#define COM_GYMJOT_CUFF_CUFF_PB_H_MAX_SIZE       com_gymjot_cuff_DeviceEvent_size
#define com_gymjot_cuff_AprilTagDetectedEvent_size 56
#define com_gymjot_cuff_BootEvent_size           9
#define com_gymjot_cuff_ClearBondsCommand_size   2
#define com_gymjot_cuff_DeviceEvent_size         1441
#define com_gymjot_cuff_ExerciseBroadcastEvent_size 1427
#define com_gymjot_cuff_ExerciseMetadata_size    1350
#define com_gymjot_cuff_ExerciseReadyEvent_size  6
#define com_gymjot_cuff_ExerciseRequestEvent_size 6
#define com_gymjot_cuff_ExerciseUpdateCommand_size 1439
#define com_gymjot_cuff_FactoryResetCommand_size 2
#define com_gymjot_cuff_MetadataEntry_size       132
#define com_gymjot_cuff_MotionDetectedEvent_size 17
#define com_gymjot_cuff_OtaCompleteCommand_size  2
#define com_gymjot_cuff_OtaStatusEvent_size      114
#define com_gymjot_cuff_PhotoChunkEvent_size     217
#define com_gymjot_cuff_PhotoMetaEvent_size      58
#define com_gymjot_cuff_PowerCommand_size        2
#define com_gymjot_cuff_PowerEvent_size          34
#define com_gymjot_cuff_RepEvent_size            80
#define com_gymjot_cuff_ResetRepsCommand_size    0
#define com_gymjot_cuff_ScanEvent_size           86
#define com_gymjot_cuff_SetTargetFpsCommand_size 5
#define com_gymjot_cuff_SetTestModeCommand_size  2
#define com_gymjot_cuff_SnapshotEvent_size       153
#define com_gymjot_cuff_SnapshotRequestCommand_size 0
#define com_gymjot_cuff_StartVideoCommand_size   9
#define com_gymjot_cuff_StatusEvent_size         43
#define com_gymjot_cuff_StopVideoCommand_size    0
#define com_gymjot_cuff_TagEvent_size            8
#define com_gymjot_cuff_TakePhotoCommand_size    2
#define com_gymjot_cuff_UpdateDeviceConfigCommand_size 29
#define com_gymjot_cuff_VideoFrameEvent_size     241

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
