/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/cuff.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_gymjot_cuff_MetadataEntry, com_gymjot_cuff_MetadataEntry, AUTO)


PB_BIND(com_gymjot_cuff_ExerciseMetadata, com_gymjot_cuff_ExerciseMetadata, 2)


PB_BIND(com_gymjot_cuff_DeviceCommand, com_gymjot_cuff_DeviceCommand, 2)


PB_BIND(com_gymjot_cuff_SetTestModeCommand, com_gymjot_cuff_SetTestModeCommand, AUTO)


PB_BIND(com_gymjot_cuff_SetTargetFpsCommand, com_gymjot_cuff_SetTargetFpsCommand, AUTO)


PB_BIND(com_gymjot_cuff_ExerciseUpdateCommand, com_gymjot_cuff_ExerciseUpdateCommand, 2)


PB_BIND(com_gymjot_cuff_ResetRepsCommand, com_gymjot_cuff_ResetRepsCommand, AUTO)


PB_BIND(com_gymjot_cuff_PowerCommand, com_gymjot_cuff_PowerCommand, AUTO)


PB_BIND(com_gymjot_cuff_FactoryResetCommand, com_gymjot_cuff_FactoryResetCommand, AUTO)


PB_BIND(com_gymjot_cuff_ClearBondsCommand, com_gymjot_cuff_ClearBondsCommand, AUTO)


PB_BIND(com_gymjot_cuff_SnapshotRequestCommand, com_gymjot_cuff_SnapshotRequestCommand, AUTO)


PB_BIND(com_gymjot_cuff_TakePhotoCommand, com_gymjot_cuff_TakePhotoCommand, AUTO)


PB_BIND(com_gymjot_cuff_UpdateDeviceConfigCommand, com_gymjot_cuff_UpdateDeviceConfigCommand, AUTO)


PB_BIND(com_gymjot_cuff_OtaBeginCommand, com_gymjot_cuff_OtaBeginCommand, AUTO)


PB_BIND(com_gymjot_cuff_OtaChunkCommand, com_gymjot_cuff_OtaChunkCommand, AUTO)


PB_BIND(com_gymjot_cuff_OtaCompleteCommand, com_gymjot_cuff_OtaCompleteCommand, AUTO)


PB_BIND(com_gymjot_cuff_DeviceEvent, com_gymjot_cuff_DeviceEvent, 2)


PB_BIND(com_gymjot_cuff_BootEvent, com_gymjot_cuff_BootEvent, AUTO)


PB_BIND(com_gymjot_cuff_StatusEvent, com_gymjot_cuff_StatusEvent, AUTO)


PB_BIND(com_gymjot_cuff_TagEvent, com_gymjot_cuff_TagEvent, AUTO)


PB_BIND(com_gymjot_cuff_ExerciseRequestEvent, com_gymjot_cuff_ExerciseRequestEvent, AUTO)


PB_BIND(com_gymjot_cuff_ExerciseBroadcastEvent, com_gymjot_cuff_ExerciseBroadcastEvent, 2)


PB_BIND(com_gymjot_cuff_ExerciseReadyEvent, com_gymjot_cuff_ExerciseReadyEvent, AUTO)


PB_BIND(com_gymjot_cuff_ScanEvent, com_gymjot_cuff_ScanEvent, AUTO)


PB_BIND(com_gymjot_cuff_RepEvent, com_gymjot_cuff_RepEvent, AUTO)


PB_BIND(com_gymjot_cuff_SnapshotEvent, com_gymjot_cuff_SnapshotEvent, AUTO)


PB_BIND(com_gymjot_cuff_OtaStatusEvent, com_gymjot_cuff_OtaStatusEvent, AUTO)


PB_BIND(com_gymjot_cuff_PhotoMetaEvent, com_gymjot_cuff_PhotoMetaEvent, AUTO)


PB_BIND(com_gymjot_cuff_PhotoChunkEvent, com_gymjot_cuff_PhotoChunkEvent, AUTO)


PB_BIND(com_gymjot_cuff_PowerEvent, com_gymjot_cuff_PowerEvent, AUTO)







